.\" Manpage for rpi
.\" Contact dougie.richardson@gmail.com to correct errors or typos.
.TH man 8 "04 Dec 2014" "0.1" "rpi man page"
.SH NAME
rpi \- toolkit for Raspberry Pi development
.SH SYNOPSIS
rpi mount
rpi umount
.SH DESCRIPTION
rpi is a collection of commands to make working with the Raspberry Pi more efficient. It's focused on kernel development.
.SH BUGS
Paths are hardcoded to Doug's VMWare fusion instance running ArchLinux.
.SH AUTHOR
Doug Richardson (dougie.richardson@gmail.com)
