.\" Manpage for rpi
.\" Contact dougie.richardson@gmail.com to correct errors or typos.
.TH man 1 "07 Dec 2014" "0.0.12" "rpi man page"
.SH NAME
rpi \- toolkit for Raspberry Pi development
.SH SYNOPSIS
.B rpi
<command>
.br
.B rpi
make [target...]
.SH DESCRIPTION
rpi is a collection of commands to make working with the Raspberry Pi more efficient. It's focused on kernel development. The current user is expected to have sudo access.
.SH COMMANDS
.TP
.B rpi mount
Mount the the 2 SD card partitions to ~/rpi_mnt/boot and ~/rpi_mnt/root. Assumes the first partition is the boot partition and second is the root.
.TP
.B rpi umount
Unmount the 2 SD card partitions.
.B rpi mkimage
Make a kernel.img suitable for the Raspberry Pi.
.TP
.B rpi cpimage
Copy kernel.img created with \fBrpi mkimage\fR to ~/rpi_mnt/boot/kernel-new.img.
.TP
.B rpi make
Run \fBmake\fR in the Linux kernel source directory.
.TP
.B rpi make menuconfig
Run \fBmake menuconfig\fR in the Linux kernel source directory.
.TP
.TP
.B rpi modules_install
Installs the kernel modules and firmware. Use this command instead of \fBrpi make modules_install firmware_install\fR because this command make sure to compile as the current user and only switches to root (using sudo) when needed to install the modules on the SD card.
.TP
.B rpi all
Builds the kernel and kernel modules, mounts the SD card partitions, installs the kernel, modules, and firmware to the SD card, and finally unmounts the SD card partitions.
.TP
.B rpi kernel
Like all, but only the kernel proper, not the modules or firmware.
.TP
.B rpi all_clean
Like all, but also does a \fBmake clean\fR on the kernel before building.
.TP
.B rpi cat
Read and print text from the usb to serial adapter connected to the Raspberry Pi. Handles resetting the tty settings of the device in case you've used gdb remote debuggin on it (which screws with the tty settings).
.TP
.B rpi cc_args
Run clang_complete's cc_args program on KERNEL_SRC to generate a clangs complete configuration.
.TP
.B rpi ctags
Run ctags on KERNEL_SRC, excluding non-ARM directories in the arch sub-directory.
.TP
.B rpi config
Dump the \fBrpi\fR configuration.
.SH BUGS
Paths are hardcoded to Doug's VMWare fusion instance running Arch Linux.
.SH AUTHOR
Doug Richardson (dougie.richardson@gmail.com)
